import { Dimensions, StyleSheet } from "react-native";
import { fonts } from "./font";

const { width, height } = Dimensions.get("window");

const colors = {
  platinum: "#E5E5E5",
  battleshipGray: "#8A8B8E",
  jet: "#2F3136",
  royalBlue: "#2764F3",
  marianBlue: "#163C90",
};

const font_sizes = {
  big: 45,
  mid: 25,
  regular: 13,
};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.jet,
  },
  topnav_wrapper: {
    backgroundColor: colors.battleshipGray,
    height: 100,
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flex: 1,
    justifyContent: "space-between",
  },
  topnav_container: {
    marginVertical: height * 0.02,
    marginHorizontal: width * 0.02,
    borderRadius: 6,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  topnav_left: {},
  topnav_right: {},
  topnav_text: {
    fontFamily: fonts.bold,
    fontSize: font_sizes.regular,
  },
  menu_container: {
    marginHorizontal: width * 0.05,
    marginVertical: height * 0.05,
    flexDirection: "column",
    gap: width * 0.05,
    flexWrap: "wrap",
  },
  menu_card: {
    borderColor: colors.battleshipGray,
    borderWidth: 1,
    borderRadius: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 15,
    width: "100%",
    height: 120,
  },
  menu_texts: {
    fontFamily: fonts.bold,
    color: colors.platinum,
  },
  menu_image_container: {
    backgroundColor: colors.jet,
    padding: 10,
    borderRadius: 6,
    marginRight: 15,
  },
  menu_image: {
    width: 50,
    height: 50,
    resizeMode: "contain",
  },
  main: {
    paddingHorizontal: width * 0.05,
    paddingVertical: height * 0.03,
    color: colors.platinum,
    fontSize: font_sizes.regular,
    fontFamily: fonts.regular,
  },
  menu_card_room: {
    borderColor: colors.battleshipGray,
    borderWidth: 1,
    borderRadius: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    height: 60,
  },
  room_image: {
    width: 30,
    height: 30,
  },
  room_image_container: {
    backgroundColor: colors.jet,
    padding: 10,
    borderRadius: 6,
    marginRight: 15,
  },
  room_title_text: {
    fontFamily: fonts.bold,
    color: colors.platinum,
    paddingRight: 15,
  },
  room_container: {
    marginHorizontal: width * 0.05,
    flexDirection: "column",
    gap: width * 0.05,
    flexWrap: "wrap",
  },
  room_card: {
    borderColor: colors.battleshipGray,
    borderWidth: 1,
    borderRadius: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 15,
    width: "100%",
    height: 80,
  },
  background_index: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  addModuleContainer2: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  addModuleWrapper2: {
    backgroundColor: colors.battleshipGray + "20",
    width: "80%",
    height: "30%",
    borderColor: colors.platinum,
    borderRadius: 10,
    borderWidth: 2,
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  addModuleCloseButton: {},
  addModuleText: {
    color: colors.platinum,
    fontSize: 15,
  },
  ModuleTextInput: {
    color: colors.platinum,
    borderWidth: 2,
    borderColor: colors.platinum,
    borderRadius: 10,
    marginVertical: 10,
    paddingVertical: 5,
    width: "100%",
  },
  AddModelContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: height * 0.005,
    paddingHorizontal: width * 0.005,
    backgroundColor: colors.battleshipGray + "20",
  },
  AddModelWrapper: {
    width: "90%",
    height: "90%",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    borderColor: colors.platinum + "90",
    borderWidth: 2,
    borderRadius: 10,
  },
  AddModelText: {
    color: colors.platinum + "90",
    fontSize: 20,
    marginVertical: 10,
  },
  AddModuleCamera: {
    width: "100%",
    height: "60%",
    borderColor: colors.platinum + "90",
    backgroundColor: colors.marianBlue,
    borderWidth: 2,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    marginHorizontal: 0,
  },
  AddModelDescriptionText: {
    borderColor: colors.platinum + "95",
    borderWidth: 2,
    borderRadius: 10,
    marginVertical: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  AddModelDescriptionText2: {
    borderColor: colors.platinum + "95",
    borderWidth: 2,
    borderRadius: 1000,
    marginVertical: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    height: 60,
  },
  AddModelText2: {
    color: colors.platinum,
    fontSize: 12,
  },
  AddModuleDescriptionMenu: {
    flex: 1,
    flexDirection: "row",
    gap: 20,
    marginBottom: 0,
  },
  AddModelText3: {
    paddingTop: 20,
    color: "green",
  },
  warningModalContainer: {
    backgroundColor: colors.jet,
    flex: 1,
    flexDirection: "column",
  },
  warningModalWrapper: {
    borderWidth: 2,
    borderRadius: 10,
    borderColor: colors.battleshipGray,
    width: "100%",
    height: "10%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  warningModalText: {
    color: colors.platinum,
    fontSize: 20,
  },
  accountContainer: {
    flex: 1,
  },
});
